/* Screen 6 — Export: nfrs.yaml, nfrs.md, ADRs from current state */
(async function () {
  UI.renderTopbar("export.html");
  const catalog = await NFR.loadCatalog();
  const out = document.getElementById("out");
  let current = "yaml";

  function gather() {
    const ctx = NFR.getContext();
    const ranked = NFR.rankNfrs(catalog, ctx).filter(n => n.tier !== "low");
    const scenarios = NFR.getScenarios();
    const priorities = NFR.getPriorities();
    const conflicts = NFR.activeConflicts(NFR.rankNfrs(catalog, ctx), "medium");
    ranked.forEach(n => { n.scenario = scenarios[n.id] || n.scenarioTemplate; });
    return { ctx, ranked, conflicts, priorities };
  }

  function yamlEscape(s){ return /[:#{}\[\],&*?|<>=!%@`"']/.test(s) ? JSON.stringify(s) : s; }

  function toYaml() {
    const { ctx, ranked, conflicts, priorities } = gather();
    let y = "# Generated by NFR Advisor — based on ISO/IEC 25010, arc42 Q42, ATAM\n";
    y += "context:\n";
    Object.keys(ctx).forEach(k => { y += `  ${k}: ${yamlEscape(String(ctx[k]))}\n`; });
    y += "nfrs:\n";
    ranked.forEach(n => {
      y += `  - id: ${n.id}\n`;
      y += `    name: ${yamlEscape(n.name)}\n`;
      y += `    category: ${n.category}\n`;
      y += `    iso: ${yamlEscape(n.iso)}\n`;
      y += `    importance: ${n.tier}\n`;
      y += `    score: ${n.score}\n`;
      y += `    scenario:\n`;
      y += `      stimulus: ${yamlEscape(n.scenario.stimulus)}\n`;
      y += `      response: ${yamlEscape(n.scenario.response)}\n`;
      y += `      measure: ${yamlEscape(n.scenario.measure)}\n`;
      y += `    fitness_function: ${yamlEscape(n.fitnessFunction)}\n`;
      y += `    tactics:\n`;
      n.tactics.forEach(t => { y += `      - ${yamlEscape(t)}\n`; });
    });
    y += "tradeoffs:\n";
    if (!conflicts.length) y += "  []\n";
    conflicts.forEach(e => {
      const w = priorities[e.key];
      y += `  - between: [${e.a.id}, ${e.b.id}]\n`;
      y += `    resolution: ${w ? ("prioritize " + w) : "UNRESOLVED"}\n`;
    });
    return y;
  }

  function toMd() {
    const { ctx, ranked, conflicts, priorities } = gather();
    let m = "# Non-Functional Requirements\n\n";
    m += "_Generated by NFR Advisor — grounded in ISO/IEC 25010, the arc42 Quality Model, and ATAM._\n\n";
    m += "## System context\n\n| Dimension | Value |\n|---|---|\n";
    Object.keys(ctx).forEach(k => { m += `| ${k} | ${ctx[k]} |\n`; });
    m += "\n## Quality requirements (by importance)\n\n";
    ["high","medium"].forEach(tier => {
      const group = ranked.filter(n => n.tier === tier);
      if (!group.length) return;
      m += `### ${tier === "high" ? "High importance" : "Medium importance"}\n\n`;
      group.forEach(n => {
        m += `#### ${n.name}\n`;
        m += `- **ISO 25010:** ${n.iso}\n`;
        m += `- **Scenario:** ${n.scenario.stimulus} → ${n.scenario.response}\n`;
        m += `- **Measure (acceptance):** ${n.scenario.measure}\n`;
        m += `- **Tactics:** ${n.tactics.join("; ")}\n`;
        m += `- **Verify:** ${n.fitnessFunction}\n\n`;
      });
    });
    m += "## Trade-offs\n\n";
    if (!conflicts.length) { m += "_No active conflicts among selected NFRs._\n"; }
    conflicts.forEach(e => {
      const w = priorities[e.key];
      m += `- **${e.a.name} ↔ ${e.b.name}** — ${w ? ("prioritize **" + (w===e.a.id?e.a.name:e.b.name) + "**") : "_unresolved_"}\n`;
    });
    return m;
  }

  function toAdr() {
    const { ctx, conflicts, priorities } = gather();
    if (!conflicts.length) return "# No trade-off ADRs\n\nNo conflicts among the selected NFRs for this context.\n";
    return conflicts.map((e, i) => {
      const w = priorities[e.key];
      const num = String(i + 1).padStart(4, "0");
      const winner = w ? (w === e.a.id ? e.a : e.b) : null;
      const loser = w ? (w === e.a.id ? e.b : e.a) : null;
      return `# ADR-${num}: Trade-off between ${e.a.name} and ${e.b.name}

## Status
${w ? "Accepted" : "Proposed (UNRESOLVED — decide on the Trade-offs screen)"}

## Context
For a ${ctx.domain} system at ${ctx.userScale} scale (availability target ${ctx.availabilityTarget}%, data sensitivity ${ctx.dataSensitivity}), the qualities **${e.a.name}** and **${e.b.name}** are both relevant but pull the design in opposite directions.

## Decision
${w ? `Prioritize **${winner.name}** over **${loser.name}** where they conflict.` : "_Not yet decided._"}

## Consequences
${w ? `- Architectural tactics will favour ${winner.name}: ${winner.tactics.slice(0,3).join("; ")}.
- Accept reduced ${loser.name}; mitigate via: ${loser.tactics.slice(0,2).join("; ")}.
- Acceptance measure to watch: ${winner.scenarioTemplate.measure}.` : "- Pending decision."}
`;
    }).join("\n---\n\n");
  }

  function content() { return current === "yaml" ? toYaml() : current === "md" ? toMd() : toAdr(); }
  function filename() { return current === "yaml" ? "nfrs.yaml" : current === "md" ? "nfrs.md" : "adr-tradeoffs.md"; }

  function render() { out.textContent = content(); }

  document.querySelectorAll("button[data-tab]").forEach(b => {
    b.addEventListener("click", () => {
      document.querySelectorAll("button[data-tab]").forEach(x => x.classList.remove("active"));
      b.classList.add("active");
      current = b.getAttribute("data-tab");
      render();
    });
  });
  document.getElementById("copyBtn").addEventListener("click", () => {
    navigator.clipboard.writeText(content());
    const btn = document.getElementById("copyBtn"); const t = btn.textContent;
    btn.textContent = "Copied!"; setTimeout(() => btn.textContent = t, 1200);
  });
  document.getElementById("dlBtn").addEventListener("click", () => {
    const blob = new Blob([content()], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob); a.download = filename(); a.click();
    URL.revokeObjectURL(a.href);
  });

  render();
})();
